const products =[
  {"id":1,"name":"Olives - Nicoise","image":"https://robohash.org/reprehenderitautexcepturi.png?size=50x50&set=set1","price":"$0.79","description":"Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue."},
{"id":2,"name":"Beer - Upper Canada Lager","image":"https://robohash.org/etharumeum.png?size=50x50&set=set1","price":"$6.83","description":"Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla."},
{"id":3,"name":"Pineapple - Canned, Rings","image":"https://robohash.org/consequunturfacereconsequatur.png?size=50x50&set=set1","price":"$2.71","description":"Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh."},
{"id":4,"name":"Wine - White, Lindemans Bin 95","image":"https://robohash.org/officiiseligendiexplicabo.png?size=50x50&set=set1","price":"$0.44","description":"Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus."},
{"id":5,"name":"Sour Puss Raspberry","image":"https://robohash.org/quisquamimpeditmolestias.png?size=50x50&set=set1","price":"$6.73","description":"Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst."},
{"id":6,"name":"Water - Evian 355 Ml","image":"https://robohash.org/doloribusautvoluptas.png?size=50x50&set=set1","price":"$9.45","description":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat."},
{"id":7,"name":"Wine - Chateauneuf Du Pape","image":"https://robohash.org/autemdeseruntvoluptate.png?size=50x50&set=set1","price":"$5.36","description":"Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit."},
{"id":8,"name":"Straw - Regular","image":"https://robohash.org/doloribusassumendavoluptas.png?size=50x50&set=set1","price":"$2.98","description":"Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices."},
{"id":9,"name":"Lobster - Base","image":"https://robohash.org/architectoofficiisdolores.png?size=50x50&set=set1","price":"$7.31","description":"Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat."},
{"id":10,"name":"English Muffin","image":"https://robohash.org/liberoidest.png?size=50x50&set=set1","price":"$3.89","description":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis."}
]

module.exports = {products}